name: release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Build
        run: bash ./build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            excel2json_*
